spring:
  #DATASOURCE BD
  datasource:
    url: jdbc:mysql://localhost:3306/lista_compras_db
    username: root
    password: viit0r

  #JPA
  jpa:
    hibernate:
      ddl-auto: none

    #SQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true